### 测试添加班级功能
GET http://localhost:8888/teacher/add-class?id=20010609&name=2019级计科三班
Accept: application/json

###
GET http://localhost:8888/teacher/add-class?id=20010609&name=2019级计科二班
Accept: application/json

### 测试根据 id 查询所有关联的 班级
GET http://localhost:8888/teacher/all-classes?id=20010609
Accept: application/json

###
GET http://localhost:8888/student/add/1?id=20192705&name=林啸扬
Accept: application/json

###
GET http://localhost:8888/student/all/8
Accept: application/json

###
GET http://localhost:8888/student/part/8?page=2&size=8
Accept: application/json

### 根据 教工号id 以及 分页条件(page=xx&size=xx) 插叙部分班级信息
GET http://localhost:8888/teacher/part-classes?id=20010609&page=1&size=8
Accept: application/json

###
